import TOCSIN
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
from bart_score import BARTScorer
# initialize the model
import numpy as np



#input by yourself
"""
print("Please enter your sentence: (Press Enter twice to start processing)")
contents = []
while True:
    line = input()
    if len(line) == 0:
        break
    contents.append(line)
sentence = "\\".join(contents)
"""

#input by copy
sentence = "In a world where the sun dipped below the horizon like a golden coin slipping into a vast ocean, a small village nestled in the valley basked in the warmth of twilight. Each evening, the villagers gathered at the old oak tree, sharing stories of their ancestors, weaving tales of bravery and love that echoed through generations. The air was filled with the scent of blooming jasmine, mingling with the laughter of children playing tag in the fading light.\nAs the stars began to twinkle like scattered diamonds across the velvet sky, an ancient storyteller emerged from the shadows. With a voice as smooth as silk, he captivated the crowd, drawing them into realms of magic and mystery. His stories spoke of daring quests, mythical creatures, and the timeless struggle between light and darkness. The villagers listened, their hearts racing with anticipation, as they traveled alongside heroes and heroines, each tale igniting the spark of imagination within them.\nIn those moments, under the vastness of the cosmos, they were reminded of their shared humanity—their dreams, their fears, and the unbreakable bonds that connected them all. The storyteller’s words wove a tapestry of hope, encouraging everyone to believe in the extraordinary power of their own stories."

deleted_sentences = TOCSIN.perturb_texts([sentence for _ in range(10)],pct=0.015)
#print(deleted_sentences)
length = len(sentence.split(' '))
print("your sentence's length:", length)
DEVICE = "cuda:0"
bart_scorer = BARTScorer(device=DEVICE, checkpoint='facebook/bart-base')
source_texts_list = [sentence]*10
values = bart_scorer.score(deleted_sentences,source_texts_list, batch_size=10)
print(values)
mean_values = np.mean(values)
output_score = -mean_values
print("Your output score:", output_score)
if length < 150:
    print("The sentence you input is too short. Please try again with a longer text that is more than 150 characters.")
else:
    if output_score > 0.2:
        print("This sentence is most probably generated by AI.")
    else:
        print("This sentence is most probably generated by humans, but with a very small chance that it was written by AI")


